### PR TITLE
Update to the README

### PR DESCRIPTION
**Pull request by jhamilt5**
README reflects changes in Makefile to build and run .iso instead of .img

### CODE REVIEW

**Comment by kkoser** [comment]
Should we also remove the suggested tweaks section? It doesn't seem appropriate for this project, as its no longer a starting point, but eventually a fully fledged OS.

**Comment by jhamilt5** [comment]
Wasn't sure if we should. I obviously removed the part about how to make an ISO. The only advantage to keeping it in would be a starting point for outsiders that happen upon our project. But I'd be fine removing it.

**Comment by kkoser** [comment]
I think removing it is best. It still exists in the base kernel repo. But we don't want people seeing this project and then thinking that those are actually like a todo list. We will develop our own list of tasks

**Comment by jhamilt5** [comment]
Removed the Tweaks and Projects section.

**Comment by kkoser** [comment]
LGTM!

**Pull request merged**
