### PR TITLE
DO NOT MERGE - First iso_open/read/close -- DO NOT MERGE

### PR DESCRIPTION
**Pull request by jhamilt5**
This is the initial implementation of iso_open/read/close. These functions need to change to use atapi-based functions to work inside of VirtualBox.

### CODE REVIEW

**Comment by rboccabe** [comment]
Does this need to be a do not merge PR, seeing as we'll have a better version up shortly?

**Comment by shuyangli** [comment]
@rboccabe you can always edit the title, but until your code is ready, please mark it as "do not merge" to prevent accidents...

**Comment by rboccabe** [comment]
@shuyangli What I meant was that I don't understand why we even created a PR at this stage, just to mark it as do not merge.

**Comment by shuyangli** [comment]
@rboccabe I think I agree with you, that's a question for @jhamilt5...

**Comment by shuyangli** [comment]
Can you guys make the directory /etc/iso and put all iso-related stuff inside?

**Comment by alexmwu** [comment]
what's the difference between this and PR 24?

**Comment by kkoser** [comment]
I think the goal of putting up DNM PRs is to share the code with the group and have it reviewed? Correct me if I'm wrong. There may a better way to do this though

**Comment by shuyangli** [comment]
@kkoser ideally we shouldn't put up dnm pr's. maybe we could coordinate through slack?

**Comment by alexmwu** [comment]
Well, I think we would want documentation of all pertinent code reviews, ideally on Github (not on Slack for sure though). So PRs are probably the best way. We could also close the PRs that aren't ready to be merged.

**Comment by rboccabe** [comment]
Closing as this was just for preliminary code review

**Pull request closed without merging**
