### PR TITLE
Implement e820 BIOS call for memory measurement

### PR DESCRIPTION
**Pull request by shuyangli**
The current implementation uses an outdated memory measurement call, which is inferior to int 0x15, eax=0xe820. This pull request implements the e820 BIOS call.

There are a few TODO's lingering in `kernelcore.s`, but the major functionality is complete.

### CODE REVIEW

**Comment by kkoser** [comment]
Please remove logs in system startup before we merge

**Comment by kkoser** [comment]
+1 verified, system works.

**Comment by kkoser** [comment]
Looks good to me, but someone else should probably check it too haha

**Comment by alexmwu** [comment]
LGTM, but did you ever figure out if you could dynamically allocate the mem_descriptor size?

**Comment by shuyangli** [comment]
@alexmwu no

**Pull request merged**
